### PR TITLE
Make sizeOfItemAtPath: function return a string with size extension instead of a number

### PR DESCRIPTION
**Pull request by rabih96**

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
Thanks for the suggestion, I will add a method such as formattedSizeOfItemAtPath instead of replacing the existing one. A numeric value could always be useful for math comparisons / sorting.

**Comment by rabih96** [comment]
Oh yes i realised i needed the old method after opening the pull request. XD

**Comment by fabiocaccamo** [comment]
Just released 1.0.9 pod, check it :)

**Comment by rabih96** [comment]
Awesome ! Thanks a lot it sure does help

**Pull request closed without merging**
